# Generated by Django 4.1.3 on 2022-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_availablesizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerflash',
            name='offer_product',
        ),
        migrations.AlterField(
            model_name='headerflash',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
