# Generated by Django 4.1.3 on 2022-12-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_username_login_customer_name_login_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, unique=True),
        ),
    ]
